version: "3.10"

services:
  db:
    build: ./postgres
    environment:
      - POSTGRES_DB=rutube-v1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgsql-sock:/var/run/postgresql
    networks:
      - web
    logging:
      driver: none
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
